-- editorial_lesson_titles_2026-07-31.sql
--
-- Rewrites 578 student-facing lesson titles that were still raw YouTube
-- keyword soup, into honest editorial titles. Audit finding, 31 July 2026.
--
-- WHY THESE WERE MISSED: the 29 July editorial pass rewrote 1703 titles, and the
-- Competishun+ / Mohit Tyagi batches imported on 30-31 July landed AFTER it, so
-- they never went through it. Measured with the repo's own rules
-- (src/titleQuality.js) against live production: 576 of 3088 lesson titles
-- (18.7%) violated them -- 351 pipe-separated keyword lists, 152 over the
-- 90-character limit, 252 with collapsed-whitespace damage, plus promotional
-- phrases and ALL-CAPS.
--
-- HOW THESE WERE WRITTEN: a 15-agent editorial pass (10 drafters working
-- course-by-course with full lesson context, then 5 adversarial reviewers) under
-- one overriding rule -- NOTHING IS INVENTED. A title may only use information
-- already in that lesson's own raw title, its chapter, and its position. Where
-- the source distinguishes lessons only by a number, the result is
-- "<Chapter> — Lecture N" rather than a guessed topic: a title promising a topic
-- the video does not cover would be worse than the keyword soup it replaced.
--
-- INDEPENDENTLY VALIDATED before generating this file, not taken on trust:
--   * 576/576 coverage of the violating set, no duplicate ids;
--   * every "before" byte-matches the live database (so this file cannot
--     silently overwrite a title someone changed in the meantime);
--   * every "after" passes titleQuality with zero issues;
--   * no title left unchanged;
--   * a fabrication sweep flagged 165 titles containing a word absent from the
--     original; all but 7 were morphological variants, and all 7 remaining were
--     correct domain expansions confirmed against the video's own chapter --
--     "N and O" -> Nitrogen/Oxygen (chapter: Groups 15 and 16), "GOC" ->
--     General Organic Chemistry, "ORM" -> Organic Reaction Mechanisms. Zero
--     actual fabrication.
--
-- ALSO FIXES 2 PRE-EXISTING DUPLICATES (course 282): Aakash published two
-- different videos (ids 2822/2823, 23 and 50 minutes long) under a byte-identical
-- title, so the lesson list showed two indistinguishable rows. Disambiguated by
-- their real position in the course, since nothing else about them is knowable
-- without watching.
--
-- REVERSIBLE: videos.source_title holds the original YouTube title. This file
-- BACKFILLS source_title from the current title wherever it is NULL *before*
-- overwriting, so the revert path stays complete:
--     update public.videos set title = source_title where source_title is not null;
--
-- Idempotent: each row applies only if the title still matches its recorded
-- "before" (or is already the "after"), and raises rather than guessing otherwise.

begin;

create temp table _title_rewrite (video_id bigint primary key, before_title text, after_title text) on commit drop;

insert into _title_rewrite (video_id, before_title, after_title) values
    (907, 'Definite Integration Part 1   IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 1'),
    (908, 'Definite Integration Part 2   IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 2'),
    (909, 'Definite Integration Part 3   IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 3'),
    (910, 'Definite Integration Part 4   IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 4'),
    (911, 'Definite Integration Part 5   IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 5'),
    (912, 'Definite Integration Part 6   IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 6'),
    (913, 'Definite Integration Part 7   IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 7'),
    (914, 'Definite Integration Part 8   IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 8'),
    (915, 'Definite Integration Part 9   IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 9'),
    (916, 'Definite Integration Part 10  IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 10'),
    (917, 'Definite Integration Part 11  IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 11'),
    (918, 'Definite Integration Part 12  IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 12'),
    (919, 'Definite Integration Part 13  IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 13'),
    (920, 'Definite Integration Part 14  IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 14'),
    (921, 'Definite Integration Part 15  IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 15'),
    (922, 'Definite Integration Part 16  IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 16'),
    (923, 'Definite Integration Part 17  IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 17'),
    (924, 'Definite Integration Part 18  IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 18'),
    (925, 'Definite Integration Part 19  IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 19'),
    (926, 'Definite Integration Part 20   IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 20'),
    (927, 'Definite Integration Part 21   IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 21'),
    (928, 'Definite Integration Part 22   IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 22'),
    (929, 'Definite Integration Part 23   IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 23'),
    (930, 'Definite Integration Part 24   IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 24'),
    (931, 'Definite Integration Part 25   IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 25'),
    (932, 'Definite Integration Part 26   IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 26'),
    (933, 'Definite Integration Part 27   IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 27'),
    (934, 'Definite Integration Part 28   IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 28'),
    (935, 'Definite Integration Part 29   IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 29'),
    (936, 'Definite Integration Part 30   IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 30'),
    (937, 'Definite Integration Part 31   IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 31'),
    (938, 'Definite Integration Part 32   IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 32'),
    (939, 'Definite Integration Part 33   IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 33'),
    (940, 'Definite Integration Part 34  IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 34'),
    (941, 'Definite Integration Part 35  IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 35'),
    (942, 'Definite Integration Part 36  IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 36'),
    (943, 'Definite Integration Part 37  IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 37'),
    (944, 'Definite Integration Part 38  IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 38'),
    (945, 'Definite Integration Part 39  IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 39'),
    (946, 'Definite Integration Part 40  IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 40'),
    (947, 'Definite Integration Part 41  IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 41'),
    (948, 'Definite Integration Part 42  IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 42'),
    (949, 'Definite Integration Part 43  IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 43'),
    (950, 'Definite Integration Part 44  IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 44'),
    (951, 'Definite Integration Part 45  IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 45'),
    (952, 'Definite Integration Part 46   IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 46'),
    (953, 'Definite Integration Part 47   IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 47'),
    (954, 'Definite Integration Part 48   IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 48'),
    (955, 'Definite Integration Part 49   IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 49'),
    (956, 'Definite Integration Part 50  IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 50'),
    (957, 'Definite Integration Part 51  IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 51'),
    (958, 'Definite Integration Part 52  IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 52'),
    (959, 'Definite Integration Part 53  IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 53'),
    (960, 'Definite Integration Part 54   IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 54'),
    (961, 'Definite Integration Part 55   IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 55'),
    (962, 'Definite Integration Part 56   IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 56'),
    (963, 'Definite Integration Part 57   IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 57'),
    (964, 'Definite Integration Part 58   IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 58'),
    (965, 'Definite Integration Part 59  IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 59'),
    (966, 'Definite Integration Part 60  IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 60'),
    (967, 'Definite Integration Part 61  IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 61'),
    (968, 'Definite Integration Part 62  IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 62'),
    (969, 'Definite Integration Part 63   IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 63'),
    (970, 'Definite Integration Part 64   IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 64'),
    (971, 'Definite Integration Part 65   IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 65'),
    (972, 'Definite Integration Part 66   IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 66'),
    (973, 'Definite Integration Part 67   IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 67'),
    (974, 'Definite Integration Part 68   IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 68'),
    (976, 'Definite Integration Part 70  IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 70'),
    (977, 'Definite Integration Part 71  IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 71'),
    (978, 'Definite Integration Part 72  IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 72'),
    (979, 'Definite Integration Part 73   IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 73'),
    (980, 'Definite Integration Part 74   IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 74'),
    (981, 'Definite Integration Part 75   IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 75'),
    (982, 'Definite Integration Part 76  IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 76'),
    (983, 'Definite Integration Part 77  IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 77'),
    (984, 'Definite Integration Part 78  IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 78'),
    (985, 'Definite Integration Part 79  IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 79'),
    (986, 'Definite Integration Part 80  IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 80'),
    (987, 'Definite Integration Part 81  IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 81'),
    (988, 'Definite Integration Part 82   IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 82'),
    (989, 'Definite Integration Part 83   IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 83'),
    (990, 'Definite Integration Part 84  IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 84'),
    (991, 'Definite Integration Part 85  IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 85'),
    (992, 'Definite Integration Part 86   IIT JEE MATHS VIDEOS', 'Definite Integration — Lecture 86'),
    (1214, 'Binomial Theorem Part 1   Jee mains and Jee advanced', 'Binomial Theorem — Part 1'),
    (1215, 'Binomial Theorem Part 2   Jee mains and Jee advanced', 'Binomial Theorem — Part 2'),
    (1220, 'Binomial Theorem Part 7   Jee mains and Jee advanced', 'Binomial Theorem — Part 7'),
    (1221, 'Binomial Theorem Part 8   Jee mains and Jee advanced', 'Binomial Theorem — Part 8'),
    (1222, 'Binomial Theorem Part 9   Jee mains and Jee advanced', 'Binomial Theorem — Part 9'),
    (1223, 'Binomial Theorem Part 10   Jee mains and Jee advanced', 'Binomial Theorem — Part 10'),
    (1224, 'Binomial Theorem Part 11   Jee mains and Jee advanced', 'Binomial Theorem — Part 11'),
    (1225, 'Binomial Theorem Part 12   Jee mains and Jee advanced', 'Binomial Theorem — Part 12'),
    (1226, 'Binomial Theorem Part 13   Jee mains and Jee advanced', 'Binomial Theorem — Part 13'),
    (1227, 'Binomial Theorem Part 14   Jee mains and Jee advanced', 'Binomial Theorem — Part 14'),
    (1231, 'Binomial Theorem Part 18  Jee mains and Jee advanced', 'Binomial Theorem — Part 18'),
    (1232, 'Binomial Theorem Part 19  Jee mains and Jee advanced', 'Binomial Theorem — Part 19'),
    (1233, 'Binomial Theorem Part 20   Jee mains and Jee advanced', 'Binomial Theorem — Part 20'),
    (1234, 'Binomial Theorem Part 21   Jee mains and Jee advanced', 'Binomial Theorem — Part 21'),
    (1235, 'Binomial Theorem Part 22   Jee mains and Jee advanced', 'Binomial Theorem — Part 22'),
    (1237, 'Binomial Theorem Part 24   Jee mains and Jee advanced', 'Binomial Theorem — Part 24'),
    (1238, 'Binomial Theorem Part 25   Jee mains and Jee advanced', 'Binomial Theorem — Part 25'),
    (1239, 'Binomial Theorem Part 26   Jee mains and Jee advanced', 'Binomial Theorem — Part 26'),
    (1240, 'Binomial Theorem Part 27   Jee mains and Jee advanced', 'Binomial Theorem — Part 27'),
    (1241, 'Binomial Theorem Part 28   Jee mains and Jee advanced', 'Binomial Theorem — Part 28'),
    (1242, 'Binomial Theorem Part 29   Jee mains and Jee advanced', 'Binomial Theorem — Part 29'),
    (1245, 'Binomial Theorem Part 32  Jee mains and Jee advanced', 'Binomial Theorem — Part 32'),
    (1246, 'Binomial Theorem Part 33  Jee mains and Jee advanced', 'Binomial Theorem — Part 33'),
    (1247, 'Binomial Theorem Part 34  Jee mains and Jee advanced', 'Binomial Theorem — Part 34'),
    (1249, 'Binomial Theorem Part 36   Jee mains and Jee advanced', 'Binomial Theorem — Part 36'),
    (1250, 'Binomial Theorem Part 37   Jee mains and Jee advanced', 'Binomial Theorem — Part 37'),
    (1251, 'Binomial Theorem Part 38   Jee mains and Jee advanced', 'Binomial Theorem — Part 38'),
    (1252, 'Binomial Theorem Part 39   Jee mains and Jee advanced', 'Binomial Theorem — Part 39'),
    (1253, 'Binomial Theorem Part 40   Jee mains and Jee advanced', 'Binomial Theorem — Part 40'),
    (1254, 'Binomial Theorem Part 41  Jee mains and Jee advanced', 'Binomial Theorem — Part 41'),
    (1255, 'Binomial Theorem Part 42  Jee mains and Jee advanced', 'Binomial Theorem — Part 42'),
    (1256, 'Binomial Theorem Part 43  Jee mains and Jee advanced', 'Binomial Theorem — Part 43'),
    (1257, 'Binomial Theorem Part 44  Jee mains and Jee advanced', 'Binomial Theorem — Part 44'),
    (1258, 'Binomial Theorem Part 45  Jee mains and Jee advanced', 'Binomial Theorem — Part 45'),
    (1259, 'Binomial Theorem Part 46  Jee mains and Jee advanced', 'Binomial Theorem — Part 46'),
    (1260, 'Binomial Theorem Part 47   Jee mains and Jee advanced', 'Binomial Theorem — Part 47'),
    (1261, 'Binomial Theorem Part 48   Jee mains and Jee advanced', 'Binomial Theorem — Part 48'),
    (1262, 'Binomial Theorem Part 49   Jee mains and Jee advanced', 'Binomial Theorem — Part 49'),
    (1263, 'Binomial Theorem Part 50   Jee mains and Jee advanced', 'Binomial Theorem — Part 50'),
    (1264, 'Binomial Theorem Part 51   Jee mains and Jee advanced', 'Binomial Theorem — Part 51'),
    (1265, 'Binomial Theorem Part 52  Jee mains and Jee advanced', 'Binomial Theorem — Part 52'),
    (1266, 'Binomial Theorem Part 53   Jee mains and Jee advanced', 'Binomial Theorem — Part 53'),
    (1267, 'Binomial Theorem Part 54   Jee mains and Jee advanced', 'Binomial Theorem — Part 54'),
    (1268, 'Binomial Theorem Part 55   Jee mains and Jee advanced', 'Binomial Theorem — Part 55'),
    (1269, 'Binomial Theorem Part 56   Jee mains and Jee advanced', 'Binomial Theorem — Part 56'),
    (1270, 'Binomial Theorem Part 57   Jee mains and Jee advanced', 'Binomial Theorem — Part 57'),
    (1271, 'Binomial Theorem Part 58   Jee mains and Jee advanced', 'Binomial Theorem — Part 58'),
    (1274, 'Binomial Theorem Part 61   Jee mains and Jee advanced', 'Binomial Theorem — Part 61'),
    (1275, 'Binomial Theorem Part 62   Jee mains and Jee advanced', 'Binomial Theorem — Part 62'),
    (1276, 'Binomial Theorem Part 63  Jee mains and Jee advanced', 'Binomial Theorem — Part 63'),
    (1277, 'Binomial Theorem Part 64   Jee mains and Jee advanced', 'Binomial Theorem — Part 64'),
    (1278, 'Binomial Theorem Part 65   Jee mains and Jee advanced', 'Binomial Theorem — Part 65'),
    (1279, 'Binomial Theorem Part 66   Jee mains and Jee advanced', 'Binomial Theorem — Part 66'),
    (1280, 'Binomial Theorem Part 67   Jee mains and Jee advanced', 'Binomial Theorem — Part 67'),
    (1281, 'Binomial Theorem Part 68   Jee mains and Jee advanced', 'Binomial Theorem — Part 68'),
    (1282, 'Binomial Theorem Part 69   Jee mains and Jee advanced', 'Binomial Theorem — Part 69'),
    (1283, 'Binomial Theorem Part 70   Jee mains and Jee advanced', 'Binomial Theorem — Part 70'),
    (1284, 'Binomial Theorem Part 71   Jee mains and Jee advanced', 'Binomial Theorem — Part 71'),
    (1285, 'Binomial Theorem Part 72   Jee mains and Jee advanced', 'Binomial Theorem — Part 72'),
    (1286, 'Binomial Theorem Part 73  Jee mains and Jee advanced', 'Binomial Theorem — Part 73'),
    (1287, 'Binomial Theorem Part 74   Jee mains and Jee advanced', 'Binomial Theorem — Part 74'),
    (1288, 'Binomial Theorem Part 75   Jee mains and Jee advanced', 'Binomial Theorem — Part 75'),
    (1289, 'Binomial Theorem Part 76    Jee mains and Jee advanced', 'Binomial Theorem — Part 76'),
    (1290, 'Binomial Theorem Part 77   Jee mains and Jee advanced', 'Binomial Theorem — Part 77'),
    (1291, 'Binomial Theorem Part 78   Jee mains and Jee advanced', 'Binomial Theorem — Part 78'),
    (1292, 'Binomial Theorem Part 79   Jee mains and Jee advanced', 'Binomial Theorem — Part 79'),
    (1293, 'Binomial Theorem Part 80   Jee mains and Jee advanced', 'Binomial Theorem — Part 80'),
    (1294, 'Binomial Theorem Part 81   Jee mains and Jee advanced', 'Binomial Theorem — Part 81'),
    (1295, 'Binomial Theorem Part 82   Jee mains and Jee advanced', 'Binomial Theorem — Part 82'),
    (1296, 'Binomial Theorem Part 83   Jee mains and Jee advanced', 'Binomial Theorem — Part 83'),
    (1297, 'Binomial Theorem Part 84  Jee mains and Jee advanced', 'Binomial Theorem — Part 84'),
    (1298, 'Binomial Theorem Part 85   Jee mains and Jee advanced', 'Binomial Theorem — Part 85'),
    (1299, 'Binomial Theorem Part 86   Jee mains and Jee advanced', 'Binomial Theorem — Part 86'),
    (1300, 'Binomial Theorem Part 87   Jee mains and Jee advanced', 'Binomial Theorem — Part 87'),
    (1301, 'Binomial Theorem Part 88  Jee mains and Jee advanced', 'Binomial Theorem — Part 88'),
    (1302, 'Binomial Theorem Part 89  Jee mains and Jee advanced', 'Binomial Theorem — Part 89'),
    (1303, 'Binomial Theorem Part 90   Jee mains and Jee advanced', 'Binomial Theorem — Part 90'),
    (1304, 'Binomial Theorem Part 91   Jee mains and Jee advanced', 'Binomial Theorem — Part 91'),
    (1305, 'Binomial Theorem Part 92   Jee mains and Jee advanced', 'Binomial Theorem — Part 92'),
    (998, 'Differentiation part  1 IIT JEE Maths', 'Differentiation — Lecture 1'),
    (999, 'Differentiation part  2 IIT JEE Maths', 'Differentiation — Lecture 2'),
    (1000, 'Differentiation part  3 IIT JEE Maths', 'Differentiation — Lecture 3'),
    (1011, 'Differentiation part  14  IIT JEE Maths', 'Differentiation — Lecture 14'),
    (1012, 'Differentiation part  15  IIT JEE Maths', 'Differentiation — Lecture 15'),
    (1013, 'Differentiation part  16  IIT JEE Maths', 'Differentiation — Lecture 16'),
    (1014, 'Differentiation part  17  IIT JEE Maths', 'Differentiation — Lecture 17'),
    (1015, 'Differentiation part  18  IIT JEE Maths', 'Differentiation — Lecture 18'),
    (1016, 'Differentiation part  19  IIT JEE Maths', 'Differentiation — Lecture 19'),
    (1017, 'Differentiation part  20  IIT JEE Maths', 'Differentiation — Lecture 20'),
    (1018, 'Differentiation part  21  IIT JEE Maths', 'Differentiation — Lecture 21'),
    (1019, 'Differentiation part  22  IIT JEE Maths', 'Differentiation — Lecture 22'),
    (1020, 'Differentiation part  23  IIT JEE Maths', 'Differentiation — Lecture 23'),
    (1021, 'Differentiation part  24  IIT JEE Maths', 'Differentiation — Lecture 24'),
    (1022, 'Differentiation part  25  IIT JEE Maths', 'Differentiation — Lecture 25'),
    (1023, 'Differentiation part  26  IIT JEE Maths', 'Differentiation — Lecture 26'),
    (1024, 'Differentiation part  27  IIT JEE Maths', 'Differentiation — Lecture 27'),
    (1025, 'Differentiation part  28  IIT JEE Maths', 'Differentiation — Lecture 28'),
    (1026, 'Differentiation part  29  IIT JEE Maths', 'Differentiation — Lecture 29'),
    (1027, 'Differentiation part  30  IIT JEE Maths', 'Differentiation — Lecture 30'),
    (1028, 'Differentiation part  31  IIT JEE Maths', 'Differentiation — Lecture 31'),
    (1029, 'Differentiation part  32  IIT JEE Maths', 'Differentiation — Lecture 32'),
    (1030, 'Differentiation part  33  IIT JEE Maths', 'Differentiation — Lecture 33'),
    (1031, 'Differentiation part  34  IIT JEE Maths', 'Differentiation — Lecture 34'),
    (1032, 'Differentiation part  35  IIT JEE Maths', 'Differentiation — Lecture 35'),
    (1033, 'Differentiation part  36  IIT JEE Maths', 'Differentiation — Lecture 36'),
    (1034, 'Differentiation part  37  IIT JEE Maths', 'Differentiation — Lecture 37'),
    (1035, 'Differentiation part  38  IIT JEE Maths', 'Differentiation — Lecture 38'),
    (1036, 'Differentiation part  39  IIT JEE Maths', 'Differentiation — Lecture 39'),
    (1037, 'Differentiation part  40  IIT JEE Maths', 'Differentiation — Lecture 40'),
    (1038, 'Differentiation part  41  IIT JEE Maths', 'Differentiation — Lecture 41'),
    (1039, 'Differentiation part  42  IIT JEE Maths', 'Differentiation — Lecture 42'),
    (1040, 'Differentiation part  43  IIT JEE Maths', 'Differentiation — Lecture 43'),
    (1041, 'Differentiation part  44  IIT JEE Maths', 'Differentiation — Lecture 44'),
    (1042, 'Differentiation part  45  IIT JEE Maths', 'Differentiation — Lecture 45'),
    (1043, 'Differentiation part  46  IIT JEE Maths', 'Differentiation — Lecture 46'),
    (1044, 'Differentiation part  47  IIT JEE Maths', 'Differentiation — Lecture 47'),
    (1045, 'Differentiation part  48  IIT JEE Maths', 'Differentiation — Lecture 48'),
    (1046, 'Differentiation part  49  IIT JEE Maths', 'Differentiation — Lecture 49'),
    (1047, 'Differentiation part  50  IIT JEE Maths', 'Differentiation — Lecture 50'),
    (1048, 'Differentiation part  51  IIT JEE Maths', 'Differentiation — Lecture 51'),
    (1049, 'Differentiation part  52  IIT JEE Maths', 'Differentiation — Lecture 52'),
    (1050, 'Differentiation part  53  IIT JEE Maths', 'Differentiation — Lecture 53'),
    (3116, 'JEE ADVANCE PRACTICE SERIES|REDOX TITRATION|NUMERICAL |EQUIVALENT CONCEPT|PHYSICAL CHEMISTRY |', 'Redox titration numerical — equivalent concept'),
    (3117, 'JEE ADVANCE PRACTICE SERIES|ROADMAP QUESTION|CARBONYL COMPOUNDS|ORGANIC CHEMISTRY |RIYA MA''AM', 'Carbonyl compounds — roadmap question'),
    (3118, 'JEE ADVANCE PRACTICE SERIES|ROADMAP QUESTION|π-bond chemistry|ORGANIC CHEMISTRY |RIYA MA''AM', 'π-bond chemistry — roadmap question'),
    (3119, 'JEE ADVANCE PRACTICE SERIES|MOLE CONCEPT|TITRATION|EQUIVALENT CONCEPT|REDOX|PHYSICAL CHEMISTRY|', 'Mole concept, titration, redox and equivalent concept'),
    (2568, 'Indian National Chemistry Olympiad 2016 | INChO 2016 | Q2 | Solutions|by NS sir | Competishun', 'INChO 2016 — Question 2 solution'),
    (2569, 'INChO 2015 |  Organic Chemistry Solutions | Q 5 | Competishun | National Olympiads | HBCSE |NS Sir', 'INChO 2015 organic chemistry — Question 5 solution'),
    (2570, 'INChO 2015 |  Organic Chemistry Solutions | Q 3 | Competishun | National Olympiads | HBCSE |NS Sir', 'INChO 2015 organic chemistry — Question 3 solution'),
    (2575, 'ISI Entrance Exam | PYQ Subjective UGB 2020 Q8 | Tough Combinatorics Question', 'ISI UGB 2020 subjective PYQ Question 8 — combinatorics'),
    (3069, 'JEE ADVANCED 2024 | PHYSICS  Paper solution | TEAM COMPETISHUN🔥', 'JEE Advanced 2024 physics paper solution'),
    (3078, 'Irodov Solutions (Mechanics) Problem 1.2 | #jeeadvanced  #jeemains', 'Irodov Mechanics — Problem 1.2'),
    (3079, 'Irodov Solutions (Mechanics) Problem 1.3 | #jeeadvanced  #jeemains', 'Irodov Mechanics — Problem 1.3'),
    (3080, 'Irodov Solutions (Mechanics) Problem 1.4 | #jeeadvanced  #jeemains', 'Irodov Mechanics — Problem 1.4'),
    (3081, 'Irodov Solutions (Mechanics) Problem 1.5 | #jeeadvanced  #jeemains', 'Irodov Mechanics — Problem 1.5'),
    (3082, 'Irodov Solutions (Mechanics) Problem 1.6 | #jeeadvanced  #jeemains', 'Irodov Mechanics — Problem 1.6'),
    (3083, 'Irodov Solutions (Mechanics) Problem 1.7 | #jeeadvanced  #jeemains', 'Irodov Mechanics — Problem 1.7'),
    (3084, 'Irodov Solutions (Mechanics) Problem 1.8 | #jeeadvanced  #jeemains', 'Irodov Mechanics — Problem 1.8'),
    (3085, 'Irodov Solutions (Mechanics) Problem 1.9 | #jeeadvanced  #jeemains', 'Irodov Mechanics — Problem 1.9'),
    (3086, 'Irodov Solutions (Mechanics) Problem 1.10 | #jeeadvanced  #jeemains', 'Irodov Mechanics — Problem 1.10'),
    (3087, 'Irodov Solutions (Mechanics) Problem 1.11 | #jeeadvanced  #jeemains', 'Irodov Mechanics — Problem 1.11'),
    (3088, 'Irodov Solutions (Mechanics) Problem 1.12 | #jeeadvanced  #jeemains', 'Irodov Mechanics — Problem 1.12'),
    (3089, 'Irodov Solutions (Mechanics) Problem 1.13 | #jeeadvanced  #jeemains', 'Irodov Mechanics — Problem 1.13'),
    (3090, 'Irodov Solutions (Mechanics) Problem 1.14 | #jeeadvanced  #jeemains', 'Irodov Mechanics — Problem 1.14'),
    (3091, 'Irodov Solutions (Mechanics) Problem 1.15 | #jeeadvanced  #jeemains', 'Irodov Mechanics — Problem 1.15'),
    (3092, 'Irodov Solutions (Mechanics) Problem 1.16 | #jeeadvanced  #jeemains', 'Irodov Mechanics — Problem 1.16'),
    (3093, 'Irodov Solutions (Mechanics) Problem 1.17 | #jeeadvanced  #jeemains', 'Irodov Mechanics — Problem 1.17'),
    (3094, 'Irodov Solutions (Mechanics) Problem 1.18 | #jeeadvanced  #jeemains', 'Irodov Mechanics — Problem 1.18'),
    (3095, 'Irodov Solutions (Mechanics) Problem 1.19 | #jeeadvanced  #jeemains', 'Irodov Mechanics — Problem 1.19'),
    (3096, 'Irodov Solutions (Mechanics) Problem 1.20 | #jeeadvanced  #jeemains', 'Irodov Mechanics — Problem 1.20'),
    (3097, 'Irodov Solutions (Mechanics) Problem 1.21 | #jeeadvanced  #jeemains', 'Irodov Mechanics — Problem 1.21'),
    (3098, 'Irodov Solutions (Mechanics) Problem 1.22 | #jeeadvanced  #jeemains', 'Irodov Mechanics — Problem 1.22'),
    (3099, 'Irodov Solutions (Mechanics) Problem 1.23 | #jeeadvanced  #jeemains', 'Irodov Mechanics — Problem 1.23'),
    (3100, 'Irodov Solutions (Mechanics) Problem 1.24 | #jeeadvanced  #jeemains', 'Irodov Mechanics — Problem 1.24'),
    (3101, 'Irodov Solutions (Mechanics) Problem 1.25 | #jeeadvanced  #jeemains', 'Irodov Mechanics — Problem 1.25'),
    (3102, 'Irodov Solutions (Mechanics) Problem 1.26 | #jeeadvanced  #jeemains', 'Irodov Mechanics — Problem 1.26'),
    (3103, 'Irodov Solutions (Mechanics) Problem 1.27 | #jeeadvanced  #jeemains', 'Irodov Mechanics — Problem 1.27'),
    (2504, 'AOD L-1 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Applications of Derivatives — Lecture 1'),
    (2505, 'AOD L-2 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Applications of Derivatives — Lecture 2'),
    (2506, 'AOD L-3 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Applications of Derivatives — Lecture 3'),
    (2507, 'AOD L-4 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Applications of Derivatives — Lecture 4'),
    (2508, 'AOD L-5 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Applications of Derivatives — Lecture 5'),
    (2509, 'AOD L-6 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Applications of Derivatives — Lecture 6'),
    (2510, 'AOD L-7 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Applications of Derivatives — Lecture 7'),
    (2511, 'AOD L-8 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Applications of Derivatives — Lecture 8'),
    (2436, 'P block N and O_L-1 | IIT JEE Chemistry Class 12 | Complete Chapter for JEE Main & Advanced', 'p-Block Nitrogen and Oxygen Family — Lecture 1'),
    (2437, 'P block N and O_L-2 | IIT JEE Chemistry Class 12 | Complete Chapter for JEE Main & Advanced', 'p-Block Nitrogen and Oxygen Family — Lecture 2'),
    (2438, 'P block N and O_L-3 | IIT JEE Chemistry Class 12 | Complete Chapter for JEE Main & Advanced', 'p-Block Nitrogen and Oxygen Family — Lecture 3'),
    (2439, 'P block N and O_L-4 | IIT JEE Chemistry Class 12 | Complete Chapter for JEE Main & Advanced', 'p-Block Nitrogen and Oxygen Family — Lecture 4'),
    (2440, 'P block N and O_L-5 | IIT JEE Chemistry Class 12 | Complete Chapter for JEE Main & Advanced', 'p-Block Nitrogen and Oxygen Family — Lecture 5'),
    (2327, 'Ellipse L-1 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Ellipse — Lecture 1'),
    (2328, 'Ellipse L-2 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Ellipse — Lecture 2'),
    (2329, 'Ellipse L-3 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Ellipse — Lecture 3'),
    (2330, 'Ellipse L-4 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Ellipse — Lecture 4'),
    (2389, 'Area L-1 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Area — Lecture 1'),
    (2390, 'Area L-2 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Area — Lecture 2'),
    (2391, 'Area L-3 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Area — Lecture 3'),
    (2495, 'Determinant L-1 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Determinants — Lecture 1'),
    (2496, 'Determinant L-2 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Determinants — Lecture 2'),
    (2497, 'Determinant L-3 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Determinants — Lecture 3'),
    (2434, 'P block group 17, 18_L-1 | IIT JEE Chemistry Class 12 | Complete Chapter for JEE Main & Advanced', 'p-Block Groups 17 and 18 — Lecture 1'),
    (2435, 'P block group 17, 18_L-2 | IIT JEE Chemistry Class 12 | Complete Chapter for JEE Main & Advanced', 'p-Block Groups 17 and 18 — Lecture 2'),
    (3070, 'Galti Se Mistake 😧| Definite int from zero to infinity | Frullani integral', 'Galti Se Mistake — Frullani Integral from Zero to Infinity'),
    (2543, 'JEE Advanced Chemistry PYQs | GOC | Must Know Every PYQ Pattern', 'General Organic Chemistry PYQs'),
    (2544, 'JEE Advanced Chemistry PYQs | Stereoisomerism | Must Know Every PYQ Pattern', 'Stereoisomerism PYQs'),
    (2545, 'JEE Advanced Chemistry PYQs | Polymers | Must Watch for Every Adv Aspirant', 'Polymers PYQs'),
    (2546, 'JEE Advanced Chemistry PYQs | ORM-IV | Must Watch for Every Adv Aspirant', 'Organic Reaction Mechanisms PYQs — Part 4'),
    (2547, 'JEE Advanced Chemistry PYQs | ORM-III | Must Watch for Every Adv Aspirant', 'Organic Reaction Mechanisms PYQs — Part 3'),
    (2548, 'JEE Advanced Chemistry PYQs | ORM-I & II | Must Watch for Every Adv Aspirant', 'Organic Reaction Mechanisms PYQs — Parts 1 and 2'),
    (2549, 'JEE Advanced Chemistry PYQs | Reduction, Oxidation, and Hydrolysis || Must Watch!', 'Reduction, Oxidation and Hydrolysis PYQs'),
    (2550, 'JEE Advanced Chemistry PYQs | Biomolecules | Most Important Questions & Concepts | Must Watch!', 'Biomolecules PYQs — Important Questions and Concepts'),
    (2551, 'JEE Advanced Chemistry PYQs | Aldehydes, Ketones & Carboxylic Acids Masterclass | Must Watch!', 'Aldehydes, Ketones and Carboxylic Acids PYQs — Lecture 9'),
    (2552, 'JEE Advanced Chemistry PYQs | Aldehydes, Ketones & Carboxylic Acids Masterclass | Must Watch!', 'Aldehydes, Ketones and Carboxylic Acids PYQs — Lecture 10'),
    (2553, 'JEE Advanced Chemistry PYQs | Aldehydes, Ketones & Carboxylic Acids Masterclass | Must Watch!', 'Aldehydes, Ketones and Carboxylic Acids PYQs — Lecture 11'),
    (2554, '20 Years of JEE Advanced PYQs | Aldehydes, Ketones & Carboxylic Acids Masterclass', 'Aldehydes, Ketones and Carboxylic Acids PYQs — Lecture 12'),
    (2555, '20 Years of JEE Advanced PYQs | Aldehydes, Ketones & Carboxylic Acids Masterclass', 'Aldehydes, Ketones and Carboxylic Acids PYQs — Lecture 13'),
    (2556, 'JEE Advanced Organic Chemistry PYQs🔥 | Aldehydes, Ketones & Carboxylic Acids | Must Watch', 'Aldehydes, Ketones and Carboxylic Acids PYQs — Lecture 14'),
    (2557, 'JEE Advanced Chemistry PYQs 🔥 | Aromatic Compounds | Master This Chapter for JEE Advanced', 'Aromatic Compounds PYQs — Lecture 15'),
    (2558, 'JEE Advanced Chemistry PYQs 🔥 | Aromatic Compounds | Master This Chapter', 'Aromatic Compounds PYQs — Lecture 16'),
    (2559, 'JEE Advanced Chemistry PYQs🔥| AROMATIC COMPOUNDS (Part-3) | Must Watch for Adv Aspirants', 'Aromatic Compounds PYQs — Part 3'),
    (2560, 'JEE Advanced Chemistry PYQs🔥| AROMATIC COMPOUNDS (Part-2) 2006 - 2025 | Must Watch for Adv Aspirants', 'Aromatic Compounds PYQs (2006-2025) — Part 2'),
    (2561, 'JEE Advanced Chemistry PYQs🔥| AROMATIC COMPOUNDS 2006 - 2025 | Must watch for every Adv aspirant!', 'Aromatic Compounds PYQs (2006-2025)'),
    (2531, 'LCD L-1 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Limits, Continuity and Differentiability — Lecture 1'),
    (2532, 'LCD L-2 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Limits, Continuity and Differentiability — Lecture 2'),
    (2533, 'LCD L-3 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Limits, Continuity and Differentiability — Lecture 3'),
    (2534, 'LCD L-4 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Limits, Continuity and Differentiability — Lecture 4'),
    (2535, 'LCD L-5 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Limits, Continuity and Differentiability — Lecture 5'),
    (2536, 'LCD L-6 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Limits, Continuity and Differentiability — Lecture 6'),
    (2537, 'LCD L-7 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Limits, Continuity and Differentiability — Lecture 7'),
    (2538, 'LCD L-8 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Limits, Continuity and Differentiability — Lecture 8'),
    (2539, 'LCD L-9 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Limits, Continuity and Differentiability — Lecture 9'),
    (2421, 'Thermodynamics_L-1 | IIT JEE Chemistry Class 11 | Complete Chapter for JEE Main & Advanced', 'Thermodynamics — Lecture 1'),
    (2422, 'Thermodynamics_L-2 | IIT JEE Chemistry Class 11 | Complete Chapter for JEE Main & Advanced', 'Thermodynamics — Lecture 2'),
    (2423, 'Thermodynamics_L-3 | IIT JEE Chemistry Class 11 | Complete Chapter for JEE Main & Advanced', 'Thermodynamics — Lecture 3'),
    (2424, 'Thermodynamics_L-4 | IIT JEE Chemistry Class 11 | Complete Chapter for JEE Main & Advanced', 'Thermodynamics — Lecture 4'),
    (2425, 'Thermodynamics_L-5 | IIT JEE Chemistry Class 11 | Complete Chapter for JEE Main & Advanced', 'Thermodynamics — Lecture 5'),
    (2426, 'Thermodynamics_L-6 | IIT JEE Chemistry Class 11 | Complete Chapter for JEE Main & Advanced', 'Thermodynamics — Lecture 6'),
    (2427, 'Thermodynamics_L-7 | IIT JEE Chemistry Class 11 | Complete Chapter for JEE Main & Advanced', 'Thermodynamics — Lecture 7'),
    (2450, 'Metallurgy_L-1 | IIT JEE Chemistry Class 12 | Complete Chapter for JEE Main & Advanced', 'Metallurgy — Lecture 1'),
    (2451, 'Metallurgy_L-2 | IIT JEE Chemistry Class 12 | Complete Chapter for JEE Main & Advanced', 'Metallurgy — Lecture 2'),
    (2452, 'Metallurgy_L-3 | IIT JEE Chemistry Class 12 | Complete Chapter for JEE Main & Advanced', 'Metallurgy — Lecture 3'),
    (2453, 'Metallurgy_L-4 | IIT JEE Chemistry Class 12 | Complete Chapter for JEE Main & Advanced', 'Metallurgy — Lecture 4'),
    (2454, 'Metallurgy_L-5 | IIT JEE Chemistry Class 12 | Complete Chapter for JEE Main & Advanced', 'Metallurgy — Lecture 5'),
    (2365, 'Differential Equation L-1 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Differential Equations — Lecture 1'),
    (2366, 'Differential Equation L-2 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Differential Equations — Lecture 2'),
    (2367, 'Differential Equation L-3 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Differential Equations — Lecture 3'),
    (2368, 'Differential Equation L-4 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Differential Equations — Lecture 4'),
    (2428, 'S-Block_L-1 | IIT JEE Chemistry Class 11 | Complete Chapter for JEE Main & Advanced', 's-Block Elements — Lecture 1'),
    (2429, 'S-Block_L-2 | IIT JEE Chemistry Class 11 | Complete Chapter for JEE Main & Advanced', 's-Block Elements — Lecture 2'),
    (2430, 'S-Block_L-3 | IIT JEE Chemistry Class 11 | Complete Chapter for JEE Main & Advanced', 's-Block Elements — Lecture 3'),
    (2571, '52nd ICHO 2020 SOLUTIONS|INTERNATIONAL CHEMISTRY OLYMPIADS|PROBLEM 1|RIYA ma''am|', 'IChO 2020 Problem 1 Solution'),
    (2572, '52nd ICHO 2020 SOLUTIONS|INTERNATIONAL CHEMISTRY OLYMPIADS|PROBLEM 7| BY RIYA MA''AM|', 'IChO 2020 Problem 7 Solution'),
    (2573, '52nd ICHO 2020 SOLUTIONS|INTERNATIONAL CHEMISTRY OLYMPIADS|PROBLEM 8|RIYA ma''am|', 'IChO 2020 Problem 8 Solution'),
    (2576, 'INMO 2023 Problem 1 Solution | Indian National Mathematics Olympiad | Praveen Agrawal (PAL Sir)', 'INMO 2023 Problem 1 Solution'),
    (3071, 'Jee Advanced Practice 2023| Total Permutation of 8 digit numbers using 0,2,3,4,20,34', 'Total permutations of 8-digit numbers using 0, 2, 3, 4, 20, 34'),
    (1126, 'Progression and Series Part 1  IIT JEE Maths', 'Progression and Series — Part 1'),
    (1127, 'Progression and Series Part 2  IIT JEE Maths', 'Progression and Series — Part 2'),
    (1128, 'Progression and Series Part 3  IIT JEE Maths', 'Progression and Series — Part 3'),
    (1129, 'Progression and Series Part 4  IIT JEE Maths', 'Progression and Series — Part 4'),
    (1130, 'Progression and Series Part 5  IIT JEE Maths', 'Progression and Series — Part 5'),
    (1131, 'Progression and Series Part 6  IIT JEE Maths', 'Progression and Series — Part 6'),
    (1132, 'Progression and Series Part 7  IIT JEE Maths', 'Progression and Series — Part 7'),
    (1133, 'Progression and Series Part 8  IIT JEE Maths', 'Progression and Series — Part 8'),
    (1134, 'Progression and Series Part 9  IIT JEE Maths', 'Progression and Series — Part 9'),
    (1135, 'Progression and Series Part 10  IIT JEE Maths', 'Progression and Series — Part 10'),
    (1136, 'Progression and Series Part 11  IIT JEE Maths', 'Progression and Series — Part 11'),
    (1148, 'Progression and Series Part 23  IIT JEE Maths', 'Progression and Series — Part 23'),
    (1157, 'Progression and Series Part 32  IIT JEE Maths', 'Progression and Series — Part 32'),
    (1158, 'Progression and Series Part 33  IIT JEE Maths', 'Progression and Series — Part 33'),
    (1159, 'Progression and Series Part 34  IIT JEE Maths', 'Progression and Series — Part 34'),
    (1191, 'Progression and Series Part 66  IIT JEE Maths', 'Progression and Series — Part 66'),
    (2515, 'FOM_L-1 | IIT JEE Math Class 11 | Complete Chapter for JEE Main & Advanced', 'Fundamentals of Mathematics — Lecture 1'),
    (2516, 'FOM_L-2 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Fundamentals of Mathematics — Lecture 2'),
    (2517, 'FOM_L-3 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Fundamentals of Mathematics — Lecture 3'),
    (2518, 'FOM_L-4 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Fundamentals of Mathematics — Lecture 4'),
    (2519, 'FOM_L-5 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Fundamentals of Mathematics — Lecture 5'),
    (2520, 'FOM_L-6 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Fundamentals of Mathematics — Lecture 6'),
    (2521, 'FOM_L-7 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Fundamentals of Mathematics — Lecture 7'),
    (2522, 'FOM_L-8 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Fundamentals of Mathematics — Lecture 8'),
    (2523, 'FOM_L-9 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Fundamentals of Mathematics — Lecture 9'),
    (2482, 'Liquid Solution_L-1 | IIT JEE Chemistry Class 12 | Complete Chapter for JEE Main & Advanced', 'Liquid Solution — Lecture 1'),
    (2483, 'Liquid Solution_L-2 | IIT JEE Chemistry Class 12 | Complete Chapter for JEE Main & Advanced', 'Liquid Solution — Lecture 2'),
    (2484, 'Liquid Solution_L-3 | IIT JEE Chemistry Class 12 | Complete Chapter for JEE Main & Advanced', 'Liquid Solution — Lecture 3'),
    (2485, 'Liquid Solution_L-4 | IIT JEE Chemistry Class 12 | Complete Chapter for JEE Main & Advanced', 'Liquid Solution — Lecture 4'),
    (2486, 'Liquid Solution_L-5 | IIT JEE Chemistry Class 12 | Complete Chapter for JEE Main & Advanced', 'Liquid Solution — Lecture 5'),
    (2487, 'Liquid Solution_L-6 | IIT JEE Chemistry Class 12 | Complete Chapter for JEE Main & Advanced', 'Liquid Solution — Lecture 6'),
    (2488, 'Liquid Solution_L-7 | IIT JEE Chemistry Class 12 | Complete Chapter for JEE Main & Advanced', 'Liquid Solution — Lecture 7'),
    (2489, 'Liquid Solution_L-8 | IIT JEE Chemistry Class 12 | Complete Chapter for JEE Main & Advanced', 'Liquid Solution — Lecture 8'),
    (2498, 'Indefinite Integration L-1 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Indefinite Integration — Lecture 1'),
    (2499, 'Indefinite Integration L-2 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Indefinite Integration — Lecture 2'),
    (2500, 'Indefinite Integration L-3 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Indefinite Integration — Lecture 3'),
    (2501, 'Indefinite Integration L-4 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Indefinite Integration — Lecture 4'),
    (2502, 'Indefinite Integration L-5 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Indefinite Integration — Lecture 5'),
    (2503, 'Indefinite Integration L-6 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Indefinite Integration — Lecture 6'),
    (2331, 'Hyperbola L-1 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Hyperbola — Lecture 1'),
    (2332, 'Hyperbola L-2 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Hyperbola — Lecture 2'),
    (2333, 'Hyperbola L-3 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Hyperbola — Lecture 3'),
    (2334, 'Hyperbola L-4 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Hyperbola — Lecture 4'),
    (2409, 'ITF_L-1 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Inverse Trigonometric Functions — Lecture 1'),
    (2410, 'ITF_L-2 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Inverse Trigonometric Functions — Lecture 2'),
    (2411, 'ITF_L-3 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Inverse Trigonometric Functions — Lecture 3'),
    (2512, 'MOD L-1 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Modulus and Graphs — Lecture 1'),
    (2513, 'MOD L-2 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Modulus and Graphs — Lecture 2'),
    (2514, 'MOD L-3 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Modulus and Graphs — Lecture 3'),
    (2480, 'Basic Inorganic Nomenclature_L-1 | IIT JEE Chemistry Class 11 | Complete Chapter for JEE Main & Adv.', 'Basic Inorganic Nomenclature — Lecture 1'),
    (2481, 'Basic Inorganic Nomenclature_L-2 | IIT JEE Chemistry Class 11 | Complete Chapter for JEE Main & Adv.', 'Basic Inorganic Nomenclature — Lecture 2'),
    (3072, 'JEE Advanced Chemistry PYQs | IUPAC | Must Know Every PYQ Pattern!', 'IUPAC — JEE Advanced Chemistry PYQs'),
    (2294, 'Relation & function_L-1 | IIT JEE Math Class 12 | Complete Chapter for JEE Main & Advanced', 'Relations and Functions — Lecture 1'),
    (2295, 'Relation & function_L-2 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Relations and Functions — Lecture 2'),
    (2296, 'Relation & function_L-3 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Relations and Functions — Lecture 3'),
    (2297, 'Relation & function_L-4 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Relations and Functions — Lecture 4'),
    (2298, 'Relation & function_L-5 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Relations and Functions — Lecture 5'),
    (2299, 'Relation & function_L-6 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Relations and Functions — Lecture 6'),
    (2300, 'Relation & function_L-7 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Relations and Functions — Lecture 7'),
    (2301, 'Relation & function_L-8 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Relations and Functions — Lecture 8'),
    (2302, 'Relation & function_L-9 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Relations and Functions — Lecture 9'),
    (2303, 'Relation & function_L-10 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Relations and Functions — Lecture 10'),
    (2304, 'Relation & function_L-11 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Relations and Functions — Lecture 11'),
    (2305, 'Relation & function_L-12 Part-I | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Adv', 'Relations and Functions — Lecture 12, Part 1'),
    (2306, 'Relation & function_L-12 Part-2| IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Adv.', 'Relations and Functions — Lecture 12, Part 2'),
    (2307, 'Relation & function_L-13 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Relations and Functions — Lecture 13'),
    (2308, 'Relation & function_L-14 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Relations and Functions — Lecture 14'),
    (2412, 'Quadratic Equation L-1 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Quadratic Equations — Lecture 1'),
    (2413, 'Quadratic Equation L-2 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Quadratic Equations — Lecture 2'),
    (2414, 'Quadratic Equation L-3 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Quadratic Equations — Lecture 3'),
    (2415, 'Quadratic Equation L-4 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Quadratic Equations — Lecture 4'),
    (2416, 'Quadratic Equation L-5 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Quadratic Equations — Lecture 5'),
    (2417, 'Quadratic Equation L-6 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Quadratic Equations — Lecture 6'),
    (2418, 'Quadratic Equation L-7 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Quadratic Equations — Lecture 7'),
    (2419, 'Quadratic Equation L-8 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Quadratic Equations — Lecture 8'),
    (2420, 'Quadratic Equation L-9 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Quadratic Equations — Lecture 9'),
    (2401, 'Sequence & Series L-1 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Sequences and Series — Lecture 1'),
    (2402, 'Sequence & Series L-2 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Sequences and Series — Lecture 2'),
    (2403, 'Sequence & Series L-3 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Sequences and Series — Lecture 3'),
    (2404, 'Sequence & Series L-4 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Sequences and Series — Lecture 4'),
    (2405, 'Sequence & Series L-5 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Sequences and Series — Lecture 5'),
    (2406, 'Sequence & Series L-6 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Sequences and Series — Lecture 6'),
    (2407, 'Sequence & Series L-7 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Sequences and Series — Lecture 7'),
    (2408, 'Sequence & Series L-8 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Sequences and Series — Lecture 8'),
    (2444, 'Qualitative analysis anion_L-1 | IIT JEE Chemistry Class 12 | Complete Chapter for JEE Main & Adv.', 'Qualitative Analysis of Anions — Lecture 1'),
    (2445, 'Qualitative analysis anion_L-2 | IIT JEE Chemistry Class 12 | Complete Chapter for JEE Main & Adv.', 'Qualitative Analysis of Anions — Lecture 2'),
    (2446, 'Qualitative analysis anion_L-3 | IIT JEE Chemistry Class 12 | Complete Chapter for JEE Main & Ad.', 'Qualitative Analysis of Anions — Lecture 3'),
    (2447, 'Qualitative analysis anion_L-4 | IIT JEE Chemistry Class 12 | Complete Chapter for JEE Main & Adv.', 'Qualitative Analysis of Anions — Lecture 4'),
    (2448, 'Qualitative analysis anion_L-5 | IIT JEE Chemistry Class 12 | Complete Chapter for JEE Main & Adv.', 'Qualitative Analysis of Anions — Lecture 5'),
    (2449, 'Qualitative analysis anion_L-6 | IIT JEE Chemistry Class 12 | Complete Chapter for JEE Main & Adv.', 'Qualitative Analysis of Anions — Lecture 6'),
    (2323, 'Parabola L-1 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Parabola — Lecture 1'),
    (2324, 'Parabola L-2 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Parabola — Lecture 2'),
    (2325, 'Parabola L-3 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Parabola — Lecture 3'),
    (2326, 'Parabola L-4 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Parabola — Lecture 4'),
    (2524, 'Equivalent Concept_L-4 | IIT JEE Chemistry Class 11 | Complete Chapter for JEE Main & Advanced', 'Equivalent Concept — Lecture 4'),
    (2525, 'Equivalent Concept_L-3 | IIT JEE Chemistry Class 11 | Complete Chapter for JEE Main & Advanced', 'Equivalent Concept — Lecture 3'),
    (2526, 'Equivalent Concept_L-2 | IIT JEE Chemistry Class 11 | Complete Chapter for JEE Main & Advanced', 'Equivalent Concept — Lecture 2'),
    (2527, 'Equivalent Concept_L-1 | IIT JEE Chemistry Class 11 | Complete Chapter for JEE Main & Advanced', 'Equivalent Concept — Lecture 1'),
    (2528, 'Introduction to Chemistry_L-1 | IIT JEE Chemistry Class 11 | Complete Chapter for JEE Main & Adv.', 'Introduction to Chemistry — Lecture 1'),
    (2529, 'Introduction to Chemistry_L-2 | IIT JEE Chemistry Class 11 | Complete Chapter for JEE Main & Adv.', 'Introduction to Chemistry — Lecture 2'),
    (2530, 'Introduction to Chemistry_L-3 | IIT JEE Chemistry Class 11 | Complete Chapter for JEE Main & Adv.', 'Introduction to Chemistry — Lecture 3'),
    (2562, 'INTERNATIONAL CHEMISTRY OLYMPIAD(ICHO) LECTURE SERIES|ORGANIC SPECTROSCOPY|INCHO|INTRODUCTION TO NMR', 'Introduction to NMR Spectroscopy'),
    (2563, 'INTERNATIONAL CHEMISTRY OLYMPIAD(ICHO) LECTURE SERIES|ORGANIC SPECTROSCOPY|INCHO| NMR lecture -2', 'NMR Spectroscopy — Lecture 2'),
    (2309, 'Vector & 3D L-1 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Vectors and 3D Geometry — Lecture 1'),
    (2310, 'Vector & 3D L-2 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Vectors and 3D Geometry — Lecture 2'),
    (2311, 'Vector & 3D L-3 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Vectors and 3D Geometry — Lecture 3'),
    (2312, 'Vector & 3D L-4 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Vectors and 3D Geometry — Lecture 4'),
    (2313, 'Vector & 3D L-5 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Vectors and 3D Geometry — Lecture 5'),
    (2314, 'Vector & 3D L-6 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Vectors and 3D Geometry — Lecture 6'),
    (2315, 'Vector & 3D L-7 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Vectors and 3D Geometry — Lecture 7'),
    (2316, 'Vector & 3D L-8 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Vectors and 3D Geometry — Lecture 8'),
    (2317, 'Vector & 3D L-9 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Vectors and 3D Geometry — Lecture 9'),
    (2318, 'Vector & 3D L-10 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Vectors and 3D Geometry — Lecture 10'),
    (2319, 'Vector & 3D L-11 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Vectors and 3D Geometry — Lecture 11'),
    (2320, 'Vector & 3D L-12 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Vectors and 3D Geometry — Lecture 12'),
    (2321, 'Vector & 3D L-13 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Vectors and 3D Geometry — Lecture 13'),
    (2322, 'Vector & 3D L-14 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Vectors and 3D Geometry — Lecture 14'),
    (2392, 'P and C L-1 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Permutations and Combinations — Lecture 1'),
    (2393, 'P and C L-2 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Permutations and Combinations — Lecture 2'),
    (2394, 'P and C L-3 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Permutations and Combinations — Lecture 3'),
    (2395, 'P and C L-4 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Permutations and Combinations — Lecture 4'),
    (2396, 'P and C L-5 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Permutations and Combinations — Lecture 5'),
    (2397, 'P and C L-6 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Permutations and Combinations — Lecture 6'),
    (2398, 'P and C L-7 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Permutations and Combinations — Lecture 7'),
    (2399, 'P and C L-8 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Permutations and Combinations — Lecture 8'),
    (2400, 'P and C L-9 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Permutations and Combinations — Lecture 9'),
    (2369, 'Straight Line L-1 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Straight Lines — Lecture 1'),
    (2370, 'Straight Line L-2 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Straight Lines — Lecture 2'),
    (2371, 'Straight Line L-3 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Straight Lines — Lecture 3'),
    (2372, 'Straight Line L-4 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Straight Lines — Lecture 4'),
    (2373, 'Straight Line L-5 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Straight Lines — Lecture 5'),
    (2374, 'Straight Line L-6 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Straight Lines — Lecture 6'),
    (2375, 'Straight Line L-7 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Straight Lines — Lecture 7'),
    (2376, 'Straight Line L-8 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Straight Lines — Lecture 8'),
    (2383, 'Definite Integration L-1 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Definite Integration — Lecture 1'),
    (2384, 'Definite Integration L-2 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Definite Integration — Lecture 2'),
    (2385, 'Definite Integration L-3 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Definite Integration — Lecture 3'),
    (2386, 'Definite Integration L-4 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Definite Integration — Lecture 4'),
    (2387, 'Definite Integration L-5 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Definite Integration — Lecture 5'),
    (2388, 'Definite Integration L-6 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Definite Integration — Lecture 6'),
    (3111, 'Le Chatelier’s Principle | Inert Gas, Pressure & Equilibrium| JEE Chemistry #alksir', 'Le Chatelier’s Principle — Inert Gas, Pressure and Equilibrium'),
    (3112, 'Bentz''s Rule in Chemical Bonding | PF₃Cl₂ Bond Lengths & JEE Advanced Concept Question #alksir', 'Bent''s Rule in Chemical Bonding — PF₃Cl₂ Bond Lengths Concept Question'),
    (3113, 'Most Expected JEE Advanced Organic Chemistry Question | Resonance Trick Explained #jee2027', 'Resonance Trick Explained — Organic Chemistry Question'),
    (3114, 'Wave Function Explained for JEE Advanced | Quantum Mechanics | JEE Chemistry Made Easy', 'Wave Function Explained — Quantum Mechanics'),
    (3115, 'JEE Advanced Titration Trick 🔥 Flow Diagram Method | Complex Redox + Precipitation Questions', 'Titration Trick — Flow Diagram Method for Redox and Precipitation Questions'),
    (2577, 'JEE Advanced Practice Series | Permutation and Combination | Multinomial Theorem | Multiple Correct', 'Permutations and Combinations — Multinomial Theorem (Multiple Correct)'),
    (2578, 'JEE Advanced Practice Series|Differential Equation|Function added with its derivative|Comprehension', 'Differential Equations — Function added with its derivative (Comprehension)'),
    (2580, 'JEE Advanced Practice Series | Geometry of Complex Number | Rohit Soni Sir', 'Geometry of Complex Numbers'),
    (2581, 'JEE Advanced Practice Series | Conditional Probability | Comprehension', 'Conditional Probability (Comprehension)'),
    (2540, 'General inorganic chemistry_L-1 | IIT JEE Chemistry Class 12 | Complete Chapter for JEE Main & Adv.', 'General Inorganic Chemistry — Lecture 1'),
    (2541, 'General inorganic chemistry_L-2 | IIT JEE Chemistry Class 12 | Complete Chapter for JEE Main & Adv.', 'General Inorganic Chemistry — Lecture 2'),
    (2542, 'General inorganic chemistry_L-3 | IIT JEE Chemistry Class 12 | Complete Chapter for JEE Main & Adv.', 'General Inorganic Chemistry — Lecture 3'),
    (3109, 'Effective Mass in Atwood Machine | Advanced Newton''s Laws | JEE Main & Advanced Physics #abjsir', 'Effective Mass in Atwood Machine — Advanced Newton''s Laws'),
    (3110, 'JEE Advanced Physics: Non-Paraxial Rays Through Plane Surface | Complete Derivation', 'Non-Paraxial Rays Through Plane Surface — Complete Derivation'),
    (2335, 'Binomial Theorem L-1 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Binomial Theorem — Lecture 1'),
    (2336, 'Binomial Theorem L-2 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Binomial Theorem — Lecture 2'),
    (2337, 'Binomial Theorem L-3 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Binomial Theorem — Lecture 3'),
    (2338, 'Binomial Theorem L-4 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Binomial Theorem — Lecture 4'),
    (2339, 'Binomial Theorem L-5 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Binomial Theorem — Lecture 5'),
    (2340, 'Binomial Theorem L-6 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Binomial Theorem — Lecture 6'),
    (2341, 'Binomial Theorem L-7 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Binomial Theorem — Lecture 7'),
    (2342, 'Binomial Theorem L-8 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Binomial Theorem — Lecture 8'),
    (2343, 'Binomial Theorem L-9 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Binomial Theorem — Lecture 9'),
    (2344, 'Binomial Theorem L-10 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Binomial Theorem — Lecture 10'),
    (2345, 'Binomial Theorem L-11 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Binomial Theorem — Lecture 11'),
    (2466, 'Gaseous state_L-1 | IIT JEE Chemistry Class 11 | Complete Chapter for JEE Main & Advanced', 'Gaseous State — Lecture 1'),
    (2467, 'Gaseous state_L-2 | IIT JEE Chemistry Class 11 | Complete Chapter for JEE Main & Advanced', 'Gaseous State — Lecture 2'),
    (2468, 'Gaseous state_L-3 | IIT JEE Chemistry Class 11 | Complete Chapter for JEE Main & Advanced', 'Gaseous State — Lecture 3'),
    (2469, 'Gaseous state_L-4 | IIT JEE Chemistry Class 11 | Complete Chapter for JEE Main & Advanced', 'Gaseous State — Lecture 4'),
    (2470, 'Gaseous state_L-5 | IIT JEE Chemistry Class 11 | Complete Chapter for JEE Main & Advanced', 'Gaseous State — Lecture 5'),
    (2471, 'Gaseous state_L-6 | IIT JEE Chemistry Class 11 | Complete Chapter for JEE Main & Advanced', 'Gaseous State — Lecture 6'),
    (2472, 'Gaseous state_L-7 | IIT JEE Chemistry Class 11 | Complete Chapter for JEE Main & Advanced', 'Gaseous State — Lecture 7'),
    (2473, 'Gaseous state_L-8 | IIT JEE Chemistry Class 11 | Complete Chapter for JEE Main & Advanced', 'Gaseous State — Lecture 8'),
    (2474, 'Gaseous state_L-9 | IIT JEE Chemistry Class 11 | Complete Chapter for JEE Main & Advanced', 'Gaseous State — Lecture 9'),
    (2475, 'Gaseous state_L-10 | IIT JEE Chemistry Class 11 | Complete Chapter for JEE Main & Advanced', 'Gaseous State — Lecture 10'),
    (2357, 'Circle L-1 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Circles — Lecture 1'),
    (2358, 'Circle L-2 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Circles — Lecture 2'),
    (2359, 'Circle L-3 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Circles — Lecture 3'),
    (2360, 'Circle L-4 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Circles — Lecture 4'),
    (2361, 'Circle L-5 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Circles — Lecture 5'),
    (2362, 'Circle L-6 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Circles — Lecture 6'),
    (2363, 'Circle L-7 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Circles — Lecture 7'),
    (2364, 'Circle L-8 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Circles — Lecture 8'),
    (2377, 'Solution of triangle L-1 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Solutions of Triangles — Lecture 1'),
    (2378, 'Solution of Triangle L-2 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Solutions of Triangles — Lecture 2'),
    (2379, 'Solution of Triangle L-3 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Solutions of Triangles — Lecture 3'),
    (2380, 'Solution of Triangle L-4 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Solutions of Triangles — Lecture 4'),
    (2381, 'Solution of Triangle L-5 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Solutions of Triangles — Lecture 5'),
    (2382, 'Solution of Triangle L-6 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Solutions of Triangles — Lecture 6'),
    (2490, 'Matrices L-1 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Matrices — Lecture 1'),
    (2491, 'Matrices L-2 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Matrices — Lecture 2'),
    (2492, 'Matrices L-3 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Matrices — Lecture 3'),
    (2493, 'Matrices L-4 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Matrices — Lecture 4'),
    (2494, 'Matrices L-5 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Matrices — Lecture 5'),
    (2455, 'D and f block elements_L-1 | IIT JEE Chemistry Class 12 | Complete Chapter for JEE Main & Advanced', 'The d and f Block Elements — Lecture 1'),
    (2456, 'D and f block elements_L-2 | IIT JEE Chemistry Class 12 | Complete Chapter for JEE Main & Advanced', 'The d and f Block Elements — Lecture 2'),
    (2457, 'D and f block elements_L-3 | IIT JEE Chemistry Class 12 | Complete Chapter for JEE Main & Advanced', 'The d and f Block Elements — Lecture 3'),
    (2458, 'D and f block elements_L-4 | IIT JEE Chemistry Class 12 | Complete Chapter for JEE Main & Advanced', 'The d and f Block Elements — Lecture 4'),
    (2431, 'Boron & Carbon Family_L-1 | IIT JEE Chemistry Class 11 | Complete Chapter for JEE Main & Advanced', 'Boron and Carbon Family — Lecture 1'),
    (2432, 'Boron & Carbon Family_L-2 | IIT JEE Chemistry Class 11 | Complete Chapter for JEE Main & Advanced', 'Boron and Carbon Family — Lecture 2'),
    (2433, 'Boron & Carbon Family_L-3 | IIT JEE Chemistry Class 11 | Complete Chapter for JEE Main & Advanced', 'Boron and Carbon Family — Lecture 3'),
    (3104, 'JEE Advanced Calculus | Quadratic Upon Quadratic Graph Trick | Local Maxima & Minima', 'Quadratic upon quadratic graph trick — local maxima and minima'),
    (3105, 'JEE Advanced Trigonometry | Toughest Cos⁷θ Question Solved in 3 Methods | Must Watch!#mohittyagisir', 'Trigonometry — toughest cos⁷θ question solved in 3 methods'),
    (3106, 'JEE Advanced FOM Tough Question | AP Trick + Telescoping Method Explained #jeeadvanced', 'Sequences and Series — AP trick and telescoping method'),
    (2604, '10 Important Questions from Plant Kingdom Class 11 Biology (Botany)', 'Plant Kingdom — 10 important questions (Botany)'),
    (2346, 'Trigonometry L-1 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Trigonometry — Lecture 1'),
    (2347, 'Trigonometry L-2 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Trigonometry — Lecture 2'),
    (2348, 'Trigonometry L-3 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Trigonometry — Lecture 3'),
    (2349, 'Trigonometry L-4 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Trigonometry — Lecture 4'),
    (2350, 'Trigonometry L-5 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Trigonometry — Lecture 5'),
    (2351, 'Trigonometry L-6 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Trigonometry — Lecture 6'),
    (2352, 'Trigonometry L-7 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Trigonometry — Lecture 7'),
    (2353, 'Trigonometry L-8 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Trigonometry — Lecture 8'),
    (2354, 'Trigonometry L-9 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Trigonometry — Lecture 9'),
    (2355, 'Trigonometry L-10 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Trigonometry — Lecture 10'),
    (2356, 'Trigonometry L-11 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Trigonometry — Lecture 11'),
    (2276, 'Complex Number L-1 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Complex Numbers — Lecture 1'),
    (2277, 'Complex Number L-2 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Complex Numbers — Lecture 2'),
    (2278, 'Complex Number L-3 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Complex Numbers — Lecture 3'),
    (2279, 'Complex Number L-4 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Complex Numbers — Lecture 4'),
    (2280, 'Complex Number L-5 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Complex Numbers — Lecture 5'),
    (2281, 'Complex Number L-6 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Complex Numbers — Lecture 6'),
    (2282, 'Complex Number L-7 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Complex Numbers — Lecture 7'),
    (2283, 'Complex Number L-8 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Complex Numbers — Lecture 8'),
    (2284, 'Complex Number L-9 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Complex Numbers — Lecture 9'),
    (2285, 'Probability L-1 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Probability — Lecture 1'),
    (2286, 'Probability L-2 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Probability — Lecture 2'),
    (2287, 'Probability L-3 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Probability — Lecture 3'),
    (2288, 'Probability L-4 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Probability — Lecture 4'),
    (2289, 'Probability L-5 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Probability — Lecture 5'),
    (2290, 'Probability L-6 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Probability — Lecture 6'),
    (2291, 'Probability L-7 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Probability — Lecture 7'),
    (2292, 'Probability L-8 | IIT JEE Mathematics Class 12 | Complete Chapter for JEE Main & Advanced', 'Probability — Lecture 8'),
    (2459, 'Solid State_L-1 | IIT JEE Chemistry Class 12 | Complete Chapter for JEE Main & Advanced', 'Solid State — Lecture 1'),
    (2460, 'Solid State_L-2 | IIT JEE Chemistry Class 12 | Complete Chapter for JEE Main & Advanced', 'Solid State — Lecture 2'),
    (2461, 'Solid State_L-3 | IIT JEE Chemistry Class 12 | Complete Chapter for JEE Main & Advanced', 'Solid State — Lecture 3'),
    (2462, 'Solid State_L-4 | IIT JEE Chemistry Class 12 | Complete Chapter for JEE Main & Advanced', 'Solid State — Lecture 4'),
    (2463, 'Solid State_L-5 | IIT JEE Chemistry Class 12 | Complete Chapter for JEE Main & Advanced', 'Solid State — Lecture 5'),
    (2464, 'Solid State_L-6 | IIT JEE Chemistry Class 12 | Complete Chapter for JEE Main & Advanced', 'Solid State — Lecture 6'),
    (2465, 'Solid State_L-7 | IIT JEE Chemistry Class 12 | Complete Chapter for JEE Main & Advanced', 'Solid State — Lecture 7'),
    (3073, 'IOQC 2020-2021 PART-2 SOLUTION|PROBLEM-2|CHEMISTRY OLYMPIADS|INCHO|ACT|IAPT|HBSCE|ESTER HYDROLYSIS', 'Chemistry Olympiad Problem 2 Solution — Ester Hydrolysis'),
    (3074, 'IOQC 2020-2021 PART-2 SOLUTIONS|PROBLEM-1|CHEMISTRY OLYMPIADS|INCHO|ACT|IAPT|HBSCE|ICHO', 'Chemistry Olympiad Problem 1 Solution'),
    (3075, 'IOQC 2020-2021 PART-2 SOLUTION|PROBLEM-3|CHEMISTRY OLYMPIADS|INCHO|ACT|IAPT|HBSCE|OZONE BASED', 'Chemistry Olympiad Problem 3 Solution — Ozone'),
    (3076, 'IOQC 2020-2021 PART-2 SOLUTION|PROBLEM-4|CHEMISTRY OLYMPIADS|INCHO|ACT|IAPT|HBSCE|ICHO|COMPETISHUN', 'Chemistry Olympiad Problem 4 Solution'),
    (3077, 'IOQC 2020-2021 PART-2 SOLUTION|PROBLEM-5|CHEMISTRY OLYMPIADS|INCHO|ACT|IAPT|HBSCE|ICHO|COMPETISHUN', 'Chemistry Olympiad Problem 5 Solution'),
    (2476, 'Periodic Table_L-1 | IIT JEE Chemistry Class 11 | Complete Chapter for JEE Main & Advanced', 'Periodic Table — Lecture 1'),
    (2477, 'Periodic Table_L-2 | IIT JEE Chemistry Class 11 | Complete Chapter for JEE Main & Advanced', 'Periodic Table — Lecture 2'),
    (2478, 'Periodic Table_L-3 | IIT JEE Chemistry Class 11 | Complete Chapter for JEE Main & Advanced', 'Periodic Table — Lecture 3'),
    (2479, 'Periodic Table_4 | IIT JEE Chemistry Class 11 | Complete Chapter for JEE Main & Advanced', 'Periodic Table — Lecture 4'),
    (2441, 'Qualitative cation_L-1 | IIT JEE Chemistry Class 12 | Complete Chapter for JEE Main & Advanced', 'Qualitative Analysis of Cations — Lecture 1'),
    (2442, 'Qualitative cation_L-2 | IIT JEE Chemistry Class 12 | Complete Chapter for JEE Main & Advanced', 'Qualitative Analysis of Cations — Lecture 2'),
    (2443, 'Qualitative cation_L-3 | IIT JEE Chemistry Class 12 | Complete Chapter for JEE Main & Advanced', 'Qualitative Analysis of Cations — Lecture 3'),
    (2274, 'Statistics L-1 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Statistics — Lecture 1'),
    (2275, 'Statistics L-2 | IIT JEE Mathematics Class 11 | Complete Chapter for JEE Main & Advanced', 'Statistics — Lecture 2'),
    (2574, 'INPhO 2019 Solutions | Physics | Olympiad | Q 1, 3 | Competishun |', 'INPhO 2019 Solutions — Questions 1 and 3'),
    (2674, '10 Most Important Questions from Reproductive Health Class 12 Biology', 'Reproductive Health — 10 Important Questions'),
    (2822, 'Skeletal System (Pt 1) - Locomotion and Movement Class 11 Biology Concept Explained', 'Skeletal System (Pt 1) — Lesson 4'),
    (2823, 'Skeletal System (Pt 1) - Locomotion and Movement Class 11 Biology Concept Explained', 'Skeletal System (Pt 1) — Lesson 5');

-- 1. Preserve the revert path FIRST. 578 rows are being rewritten and many
--    have never been edited, so their current title IS the raw YouTube original.
update public.videos v
   set source_title = v.title
  from _title_rewrite t
 where v.id = t.video_id
   and v.source_title is null;

-- 2. Apply, refusing to overwrite anything that has drifted.
do $apply$
declare
  r record;
  v_current text;
  v_applied int := 0;
  v_skipped int := 0;
begin
  for r in select * from _title_rewrite loop
    select title into v_current from public.videos where id = r.video_id;
    if v_current is null then
      raise exception 'video % not found', r.video_id;
    elsif v_current = r.after_title then
      v_skipped := v_skipped + 1;           -- already applied (safe re-run)
    elsif v_current is distinct from r.before_title then
      raise exception
        'video % no longer has the expected title. expected %, found % -- someone edited it, refusing to overwrite',
        r.video_id, r.before_title, v_current;
    else
      update public.videos
         set title = r.after_title, title_review_status = 'approved', updated_at = now()
       where id = r.video_id;
      v_applied := v_applied + 1;
    end if;
  end loop;
  raise notice 'applied % title(s), % already current', v_applied, v_skipped;
end
$apply$;

-- ---------------------------------------------------------------------
-- SELF-VERIFICATION
-- ---------------------------------------------------------------------
do $verify$
declare
  v_wrong int;
  v_norevert int;
  v_dupes int;
begin
  select count(*) into v_wrong
    from public.videos v join _title_rewrite t on t.video_id = v.id
   where v.title is distinct from t.after_title;
  if v_wrong <> 0 then
    raise exception '% title(s) did not end up as intended', v_wrong;
  end if;

  select count(*) into v_norevert
    from public.videos v join _title_rewrite t on t.video_id = v.id
   where v.source_title is null;
  if v_norevert <> 0 then
    raise exception '% rewritten row(s) have no source_title, so they cannot be reverted', v_norevert;
  end if;

  -- No course may contain two lessons rendering as the same string.
  select count(*) into v_dupes from (
    select pv.playlist_id, v.title
      from public.playlist_videos pv
      join public.videos v on v.id = pv.video_id
     group by pv.playlist_id, v.title
    having count(*) > 1
  ) d;
  if v_dupes <> 0 then
    raise exception '% course/title pair(s) are duplicated within a course', v_dupes;
  end if;

  raise notice 'SELF-TEST PASSED: 578 titles rewritten, every one revertible via source_title, no duplicate lesson titles within any course.';
end
$verify$;

commit;
