-- AUTO-GENERATED by buildContentQualityStagingDelta.js — do not edit.
-- v10 CONTENT-QUALITY DELTA — DISPOSABLE STAGING ONLY.
-- Apply after staging_bootstrap.sql and faculty_staging_delta.sql.
-- Contains no credentials and performs no connection of any kind.


-- ============================================================
-- src/migrations/content_quality_v10.sql
-- ============================================================

-- ============================================================
-- content_quality_v10.sql — reviewed titles + faculty completeness
--
-- Apply after teachers_v7.sql and teachers_v7_import.sql.
-- Additive and non-destructive: raw/source titles and legacy teacher text are
-- preserved. Nothing infers identity from equal-looking names.
-- ============================================================

alter table public.playlists add column if not exists source_title text;
alter table public.playlists add column if not exists source_title_changed boolean not null default false;
alter table public.playlists add column if not exists title_review_status text not null default 'pending';
alter table public.playlists add column if not exists faculty_credit_status text not null default 'pending';

update public.playlists
   set source_title = title
 where source_title is null;

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'playlists_title_review_status_check') then
    alter table public.playlists add constraint playlists_title_review_status_check
      check (title_review_status in ('pending','approved'));
  end if;
  if not exists (select 1 from pg_constraint where conname = 'playlists_faculty_credit_status_check') then
    alter table public.playlists add constraint playlists_faculty_credit_status_check
      check (faculty_credit_status in ('pending','identified','team','unknown'));
  end if;
end $$;

create table if not exists public.playlist_quality_reviews (
  id bigint generated always as identity primary key,
  playlist_id bigint not null references public.playlists(id) on delete cascade,
  before_state jsonb not null,
  after_state jsonb not null,
  note text,
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz not null default now()
);
create index if not exists idx_pqr_playlist_time
  on public.playlist_quality_reviews (playlist_id, reviewed_at desc);

alter table public.playlist_quality_reviews enable row level security;
drop policy if exists "admin reads quality reviews" on public.playlist_quality_reviews;
create policy "admin reads quality reviews" on public.playlist_quality_reviews
  for select to authenticated using (public.is_admin());

-- Direct writes would bypass the review transaction and its validations.
revoke all on public.playlist_quality_reviews from public, anon, authenticated, service_role;
grant select on public.playlist_quality_reviews to authenticated, service_role;

create or replace function public.playlist_quality_missing(p_playlist_id bigint)
returns text[] language sql stable security definer set search_path = '' as $$
  select array_remove(array[
    case when p.title_review_status <> 'approved' then 'title-review' end,
    case when p.source_title is null or btrim(p.source_title) = '' then 'source-title' end,
    case when p.source_title_changed then 'source-title-changed' end,
    case when p.faculty_credit_status not in ('identified','team') then 'faculty-credit' end,
    case when p.faculty_credit_status = 'identified' and not exists (
      select 1 from public.playlist_teachers pt where pt.playlist_id = p.id
    ) then 'faculty-link' end,
    case when p.faculty_credit_status = 'team' and exists (
      select 1 from public.playlist_teachers pt where pt.playlist_id = p.id
    ) then 'faculty-team-conflict' end,
    case when p.content_type is null then 'course-type' end,
    case when p.language is null then 'language' end,
    case when p.difficulty is null then 'difficulty' end,
    case when p.subject_id is null then 'subject' end,
    case when not exists (
      select 1 from public.playlist_learning_goals plg where plg.playlist_id = p.id
    ) then 'learning-goal' end,
    case when not exists (
      select 1 from public.playlist_class_levels pcl where pcl.playlist_id = p.id
    ) then 'class-level' end,
    case when not exists (
      select 1 from public.playlist_videos pv where pv.playlist_id = p.id
    ) then 'lessons' end,
    case when exists (
      select 1
        from public.playlist_videos pv
        join public.videos v on v.id = pv.video_id
       where pv.playlist_id = p.id and v.chapter_id is null
    ) then 'lesson-chapter' end
  ]::text[], null::text)
  from public.playlists p where p.id = p_playlist_id;
$$;

create or replace function public.content_quality_capability()
returns jsonb language plpgsql stable security definer set search_path = '' as $$
begin
  if not (public.is_admin() or auth.role() = 'service_role'
          or session_user in ('postgres','supabase_admin')) then
    raise exception 'not authorized' using errcode = '42501';
  end if;
  return jsonb_build_object(
    'quality_review_supported', true,
    'source_title_supported', true,
    'faculty_identity_required_for_identified', true,
    'automatic_identity_resolution', false);
end; $$;

create or replace function public.get_content_quality_queue(
  p_ready boolean default false, p_limit int default 100, p_offset int default 0)
returns table (
  playlist_id bigint, display_title text, source_title text, legacy_teacher text,
  institute text, subject text, content_type text, language text, difficulty text,
  title_review_status text, faculty_credit_status text, source_title_changed boolean,
  faculty jsonb, missing_fields text[], quality_ready boolean
)
language plpgsql stable security definer set search_path = '' as $$
begin
  if not (public.is_admin() or auth.role() = 'service_role'
          or session_user in ('postgres','supabase_admin')) then
    raise exception 'not authorized' using errcode = '42501';
  end if;
  if p_limit < 1 or p_limit > 200 or p_offset < 0 then
    raise exception 'invalid queue bounds';
  end if;

  return query
  select p.id, p.title, p.source_title, p.teacher, ic.name, s.name,
         p.content_type, p.language, p.difficulty,
         p.title_review_status, p.faculty_credit_status, p.source_title_changed,
         coalesce((
           select jsonb_agg(jsonb_build_object(
             'teacher_id', t.id, 'display_name', t.display_name,
             'verified', t.verified, 'position', pt.position
           ) order by pt.position)
           from public.playlist_teachers pt
           join public.teachers t on t.id = pt.teacher_id
           where pt.playlist_id = p.id
         ), '[]'::jsonb),
         q.missing,
         cardinality(q.missing) = 0
    from public.playlists p
    join public.institutes_channels ic on ic.id = p.channel_id
    left join public.subjects s on s.id = p.subject_id
    cross join lateral (select public.playlist_quality_missing(p.id) as missing) q
   where (cardinality(q.missing) = 0) = p_ready
   order by cardinality(q.missing) desc, p.id
   limit p_limit offset p_offset;
end; $$;

create or replace function public.review_playlist_quality(
  p_playlist_id bigint,
  p_display_title text,
  p_teacher_ids bigint[],
  p_faculty_status text,
  p_content_type text,
  p_language text,
  p_difficulty text,
  p_note text default null
)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare
  p public.playlists%rowtype;
  v_title text;
  v_before jsonb;
  v_after jsonb;
  v_missing text[];
begin
  if not (public.is_admin() or auth.role() = 'service_role'
          or session_user in ('postgres','supabase_admin')) then
    raise exception 'not authorized' using errcode = '42501';
  end if;

  select * into p from public.playlists where id = p_playlist_id for update;
  if not found then raise exception 'unknown playlist_id %', p_playlist_id; end if;

  v_title := regexp_replace(btrim(coalesce(p_display_title, '')), '\s+', ' ', 'g');
  if char_length(v_title) < 3 or char_length(v_title) > 90 then
    raise exception 'display title must contain 3 to 90 characters';
  end if;
  if p_teacher_ids is null then raise exception 'teacher_ids must be explicit'; end if;
  if p_faculty_status not in ('identified','team','unknown') then
    raise exception 'invalid faculty status %', p_faculty_status;
  end if;
  if p_faculty_status = 'identified' and cardinality(p_teacher_ids) = 0 then
    raise exception 'identified faculty requires at least one teacher id';
  end if;
  if p_faculty_status = 'team' and cardinality(p_teacher_ids) <> 0 then
    raise exception 'team credit cannot carry individual teacher ids';
  end if;
  if p_faculty_status = 'team' and char_length(btrim(coalesce(p_note,''))) < 3 then
    raise exception 'team credit requires an editorial note';
  end if;
  if p_content_type not in ('full-course','one-shot','revision','pyq','practice') then
    raise exception 'invalid content_type %', p_content_type;
  end if;
  if p_language not in ('hindi','english','hinglish') then
    raise exception 'invalid language %', p_language;
  end if;
  if p_difficulty not in ('beginner','intermediate','advanced') then
    raise exception 'invalid difficulty %', p_difficulty;
  end if;

  v_before := jsonb_build_object(
    'title', p.title, 'title_review_status', p.title_review_status,
    'faculty_credit_status', p.faculty_credit_status,
    'content_type', p.content_type, 'language', p.language, 'difficulty', p.difficulty,
    'teacher_ids', coalesce((select jsonb_agg(pt.teacher_id order by pt.position)
      from public.playlist_teachers pt where pt.playlist_id = p.id), '[]'::jsonb));

  -- Identity replacement stays delegated to the v7 write contract. It
  -- validates duplicate/unknown ids before deleting existing links.
  perform public.set_playlist_teachers(p.id, p_teacher_ids);

  update public.playlists
     set title = v_title,
         title_review_status = 'approved',
         faculty_credit_status = p_faculty_status,
         content_type = p_content_type,
         language = p_language,
         difficulty = p_difficulty,
         source_title_changed = false
   where id = p.id;

  v_after := jsonb_build_object(
    'title', v_title, 'title_review_status', 'approved',
    'faculty_credit_status', p_faculty_status,
    'content_type', p_content_type, 'language', p_language, 'difficulty', p_difficulty,
    'teacher_ids', to_jsonb(p_teacher_ids));
  insert into public.playlist_quality_reviews
    (playlist_id, before_state, after_state, note, reviewed_by)
  values (p.id, v_before, v_after, nullif(btrim(p_note), ''), auth.uid());

  v_missing := public.playlist_quality_missing(p.id);
  return jsonb_build_object('playlist_id', p.id, 'missing_fields', v_missing,
    'quality_ready', cardinality(v_missing) = 0);
end; $$;

-- Captures the exact YouTube playlist title while leaving the curated display
-- title under the base importer's merge/replace contract.
create or replace function public.import_playlist_with_quality(
  payload jsonb, mode text default 'merge')
returns jsonb language plpgsql security definer set search_path = '' as $$
declare v_source text; v_result jsonb; v_playlist_id bigint; v_old_source text;
begin
  if not (public.is_admin() or auth.role() = 'service_role') then
    raise exception 'not authorized to import' using errcode = '42501';
  end if;
  v_source := btrim(coalesce(payload->>'source_title',''));
  if v_source = '' or char_length(v_source) > 500 then
    raise exception 'source_title is required and must be at most 500 characters';
  end if;

  v_result := public.import_playlist(payload - 'source_title', mode);
  v_playlist_id := (v_result->>'playlist_id')::bigint;
  select source_title into v_old_source from public.playlists where id = v_playlist_id for update;
  update public.playlists
     set source_title = v_source,
         source_title_changed = v_old_source is not null and v_old_source is distinct from v_source
   where id = v_playlist_id;
  return v_result || jsonb_build_object('source_title_captured', true);
end; $$;

-- Replace the v7 wrapper so source-title capture and faculty links remain one
-- transaction. Old callers without source_title continue to work.
create or replace function public.import_playlist_with_teachers(
  payload jsonb, mode text default 'merge')
returns jsonb language plpgsql security definer set search_path = '' as $$
declare v_ids bigint[]; v_result jsonb; v_playlist_id bigint; v_source text; v_old_source text;
begin
  if not (public.is_admin() or auth.role() = 'service_role') then
    raise exception 'not authorized to import' using errcode = '42501';
  end if;
  v_ids := public.validate_teacher_ids_payload(payload);
  v_source := nullif(btrim(coalesce(payload->>'source_title','')), '');
  if v_source is not null and char_length(v_source) > 500 then
    raise exception 'source_title must be at most 500 characters';
  end if;

  v_result := public.import_playlist(payload - 'teacher_ids' - 'source_title', mode);
  v_playlist_id := (v_result->>'playlist_id')::bigint;
  perform public.set_playlist_teachers(v_playlist_id, v_ids);
  update public.playlists
     set faculty_credit_status = case when cardinality(v_ids) > 0 then 'identified' else 'pending' end
   where id = v_playlist_id;
  if v_source is not null then
    select source_title into v_old_source from public.playlists where id = v_playlist_id for update;
    update public.playlists
       set source_title = v_source,
           source_title_changed = v_old_source is not null and v_old_source is distinct from v_source
     where id = v_playlist_id;
  end if;
  return v_result || jsonb_build_object(
    'teachers', cardinality(v_ids), 'teacher_links_replaced', true,
    'source_title_captured', v_source is not null);
end; $$;

revoke all on function public.playlist_quality_missing(bigint) from public, anon, authenticated, service_role;
revoke all on function public.content_quality_capability() from public, anon;
revoke all on function public.get_content_quality_queue(boolean, int, int) from public, anon;
revoke all on function public.review_playlist_quality(bigint,text,bigint[],text,text,text,text,text) from public, anon;
revoke all on function public.import_playlist_with_quality(jsonb,text) from public, anon;
revoke all on function public.import_playlist_with_teachers(jsonb,text) from public, anon;

grant execute on function public.content_quality_capability() to authenticated, service_role;
grant execute on function public.get_content_quality_queue(boolean, int, int) to authenticated, service_role;
grant execute on function public.review_playlist_quality(bigint,text,bigint[],text,text,text,text,text) to authenticated, service_role;
grant execute on function public.import_playlist_with_quality(jsonb,text) to authenticated, service_role;
grant execute on function public.import_playlist_with_teachers(jsonb,text) to authenticated, service_role;

