// buildStagingBootstrap.js — concatenate every schema/migration file, in the
// order they must run, into ONE file you can paste into a fresh (staging)
// Supabase SQL Editor. Also appends a tiny seed the integration tests need.
//
// Run: node src/scripts/buildStagingBootstrap.js
// Output: staging_bootstrap.sql (git-ignored; safe — contains no secrets)
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "../..");

// Order matters — later files depend on earlier ones.
const ORDER = [
  "schema.sql",                                   // channels/categories/subjects/chapters/videos + RLS + seed
  "community_schema.sql",                         // profiles, playlists, ratings, comments + triggers
  "courses_data.sql",                             // tags/teacher + get_chapter_courses v1
  "admin_policies.sql",                           // is_admin() + admin insert policies
  "src/migrations/profile_public_identity_privacy_v1.sql", // browser roles read profile username only
  "playlist_idempotency.sql",                     // playlists.youtube_playlist_id
  "src/migrations/add_class_levels.sql",
  "src/migrations/learning_goals_and_class_levels.sql",
  "src/migrations/video_playlist_metadata.sql",
  "src/migrations/structured_ratings.sql",
  "src/migrations/fix_rating_trigger.sql",
  "src/migrations/content_reports.sql",
  "src/migrations/import_rpc.sql",                // audience_focus + import v1
  "src/migrations/import_playlist_v2.sql",        // hardened import (what production is closest to)
  "src/migrations/import_playlist_v4.sql",        // functions only — creates NO trigger
  "src/migrations/import_playlist_v6.sql",        // v6 delta: category<->goal, hardened validation, migrate fn
  "src/migrations/staging_test_helpers.sql",      // STAGING ONLY — test inspection/fixture helpers
  "src/migrations/staging_drift_fixtures.sql",    // manufactures every non-blocking drift direction
  "src/migrations/v6_class_levels_migration.sql", // calls migrate_class_levels(): audit -> backfill -> verify -> triggers
];
// v3 is deliberately ABSENT. It was never applied to any database, so it is not
// part of any real upgrade path — and running it here would both install its
// destructive one-line "repair" and create the derived-array trigger, after
// which the fixtures below could no longer drift and would prove nothing.
// The real path this reproduces is v2 -> v4, which is production's path.
//
// The fixtures sit between the v4 functions and the v4 migration because that
// is the only window in which the array can still drift: before the migration,
// no derived-array trigger exists.

// The integration suite resolves references by slug and needs one Physics
// chapter to exist. Categories/subjects are already seeded by schema.sql.
const SEED = `
-- ============================================================
--  STAGING TEST SEED (safe: reference data only, no content)
-- ============================================================
insert into public.chapters (subject_id, name, slug, display_order)
select s.id, 'Staging Test Chapter', 'staging-test-chapter', 999
from public.subjects s where s.slug = 'physics'
on conflict (subject_id, slug) do nothing;

-- The integration suite refuses to run unless the database says it is NOT
-- production (blocker 6). Production simply never receives this row.
insert into public.app_environment (id, name) values (true, 'staging')
on conflict (id) do update set name = excluded.name;
`;

let out = `-- AUTO-GENERATED by buildStagingBootstrap.js — do not edit.
-- Paste into a FRESH (staging) Supabase project's SQL Editor and Run.
-- Contains NO secrets. Safe to share.\n`;

let missing = [];
for (const rel of ORDER) {
  const p = resolve(root, rel);
  if (!existsSync(p)) { missing.push(rel); continue; }
  out += `\n\n-- ============================================================\n`;
  out += `-- ${rel}\n`;
  out += `-- ============================================================\n\n`;
  out += readFileSync(p, "utf8");
}
out += `\n${SEED}`;

writeFileSync(resolve(root, "staging_bootstrap.sql"), out, "utf8");
console.log(`✓ staging_bootstrap.sql written (${ORDER.length - missing.length}/${ORDER.length} files, ${Math.round(out.length / 1024)} KB)`);
if (missing.length) console.log(`  ⚠ missing: ${missing.join(", ")}`);
