// buildProductionMigration.js — assemble the PRODUCTION migration.
//
// This is deliberately NOT buildStagingBootstrap.js. Production already has the
// base schema and the v1/v2-era functions; it needs only the delta. It must
// never receive the staging test helpers, the drift fixtures, or the
// app_environment seed row.
//
// The builder refuses to emit a file containing any of those, so a staging
// artefact cannot reach production through a careless edit to ORDER.
//
// Run:    node src/scripts/buildProductionMigration.js
// Output: production/production_migration.sql  +  .sha256.txt
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { createHash } from "node:crypto";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "../..");

// Order matters. Everything here is safe for production.
const ORDER = [
  "src/migrations/v6_prod_legacy_cleanup.sql",     // drop the v1 1-arg import_playlist (production only had v1, never v2)
  "src/migrations/import_playlist_v4.sql",         // functions + reference data; creates NO trigger
  "src/migrations/import_playlist_v6.sql",         // v6 delta (category<->goal, hardened validation, migrate fn)
  "src/migrations/v6_2_grant_tightening.sql",      // revoke EXECUTE from `authenticated`
  "src/migrations/v6_class_levels_migration.sql",  // select migrate_class_levels(true)
];

// Anything matching these must never appear in the production file.
const FORBIDDEN_FILES = /staging|fixture|drift_fixtures|test_helpers/i;
const FORBIDDEN_CONTENT = [
  [/insert\s+into\s+public\.app_environment/i, "app_environment seed row (staging marker)"],
  [/DRIFTFX/i, "drift fixture rows"],
  [/seed_blocking_drift_fixture\s*\(\s*\)\s*returns/i, "blocking-drift fixture function definition"],
  [/create\s+or\s+replace\s+function\s+public\.__assert_not_production/i, "staging-only assertion helper"],
  [/create\s+or\s+replace\s+function\s+public\.has_trigger/i, "test-only trigger inspector"],
  [/__fixture_playlist/i, "fixture helper"],
];

for (const rel of ORDER) {
  if (FORBIDDEN_FILES.test(rel)) {
    console.error(`REFUSING: "${rel}" looks like a staging artefact and must not go to production.`);
    process.exit(1);
  }
}

let out = `-- ============================================================
--  PRODUCTION MIGRATION — edu-library importer/taxonomy hardening
--
--  Generated by src/scripts/buildProductionMigration.js. Do not edit by hand;
--  edit the sources and regenerate, or the SHA-256 manifest stops matching.
--
--  Apply to production ONLY after:
--    1. a fresh database backup exists and has been verified restorable
--    2. \`npm run drift:report\` has been run against production and reviewed
--    3. the SHA-256 below matches
--
--  The Supabase SQL Editor runs a multi-statement script as ONE implicit
--  transaction, so any error rolls the whole migration back. There is no
--  half-applied state to clean up.
--
--  Contains NO staging helpers, NO drift fixtures, and NO app_environment
--  seed row. public.app_environment is CREATED (empty) on purpose: the
--  integration suite refuses to run against a database with no environment
--  marker, so an empty table is what keeps production permanently off-limits
--  to the test harness.
-- ============================================================

`;

const missing = [];
for (const rel of ORDER) {
  const p = resolve(root, rel);
  if (!existsSync(p)) { missing.push(rel); continue; }
  out += `\n\n-- ============================================================\n`;
  out += `-- ${rel}\n`;
  out += `-- ============================================================\n\n`;
  out += readFileSync(p, "utf8");
}
if (missing.length) {
  console.error(`REFUSING: missing source files: ${missing.join(", ")}`);
  process.exit(1);
}

// Self-check the assembled text before writing anything.
const problems = [];
for (const [re, label] of FORBIDDEN_CONTENT) if (re.test(out)) problems.push(label);
if (problems.length) {
  console.error("REFUSING to write a production file containing staging artefacts:");
  for (const p of problems) console.error(`   - ${p}`);
  process.exit(1);
}

const dir = resolve(root, "production");
if (!existsSync(dir)) mkdirSync(dir);
const outPath = resolve(dir, "production_migration.sql");
writeFileSync(outPath, out, "utf8");

const hash = createHash("sha256").update(readFileSync(outPath)).digest("hex");
const bytes = readFileSync(outPath).length;
const lines = out.split("\n").length;

writeFileSync(resolve(dir, "production_migration.sha256.txt"),
`production_migration.sql — expected SHA-256
===========================================

${hash}  production_migration.sql

Size:  ${bytes.toLocaleString("en-US")} bytes
Lines: ${lines.toLocaleString("en-US")}

Verify on Windows (PowerShell):

    Get-FileHash -Algorithm SHA256 "production\\production_migration.sql"

The Hash column must equal the value above, case-insensitively. If it does not
match, DO NOT run the file.

Bundled, in order:
${ORDER.map((r, i) => `  ${i + 1}. ${r}`).join("\n")}

Verified ABSENT by the builder: staging test helpers, drift fixtures,
app_environment seed row, blocking-drift functions, fixture helpers.

Contains no credentials.
`, "utf8");

console.log(`✓ production/production_migration.sql  (${ORDER.length} files, ${Math.round(bytes / 1024)} KB, ${lines} lines)`);
console.log(`  sha256: ${hash}`);
console.log(`  self-check passed: no staging artefacts present`);
