// Build the isolated Phase 4 faculty delta for a FRESH disposable staging
// project. This never changes staging_bootstrap.sql or the production builder.
//
// Run:
//   npm run build:faculty-staging
//
// Apply staging_bootstrap.sql first, then the generated faculty_staging_delta.sql.
import { createHash } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const order = [
  "src/migrations/teachers_v7.sql",
  "src/migrations/teachers_v7_import.sql",
  "src/migrations/teachers_v7_admin_ui.sql",
  "src/migrations/universal_search.sql",
];

const missing = order.filter((rel) => !existsSync(resolve(root, rel)));
if (missing.length) {
  console.error(`Refusing to build: missing ${missing.join(", ")}`);
  process.exit(1);
}

let sql = `-- AUTO-GENERATED by buildFacultyStagingDelta.js — do not edit.
-- PHASE 4 FACULTY DELTA — DISPOSABLE STAGING ONLY.
-- Apply only after staging_bootstrap.sql in a fresh staging Supabase project.
-- This file contains no credentials and performs no production connection.
`;

for (const rel of order) {
  sql += `\n\n-- ============================================================\n`;
  sql += `-- ${rel}\n`;
  sql += `-- ============================================================\n\n`;
  sql += readFileSync(resolve(root, rel), "utf8");
}

const output = resolve(root, "faculty_staging_delta.sql");
const hashFile = resolve(root, "faculty_staging_delta.sha256.txt");
writeFileSync(output, sql, "utf8");
const sha = createHash("sha256").update(Buffer.from(sql, "utf8")).digest("hex");
writeFileSync(hashFile, `${sha}  faculty_staging_delta.sql\n`, "utf8");

console.log(`✓ faculty_staging_delta.sql written (${order.length} files, ${Math.round(Buffer.byteLength(sql) / 1024)} KB)`);
console.log(`  sha256: ${sha}`);
console.log("  target: fresh disposable staging only; production builder unchanged");
