// Build the isolated v9 navigation/facet delta for disposable staging only.
// It does not modify the verified bootstrap or production migration.
import { createHash } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const sources = ["src/migrations/catalog_navigation_v9.sql"];
const missing = sources.filter((rel) => !existsSync(resolve(root, rel)));
if (missing.length) {
  console.error(`Refusing to build: missing ${missing.join(", ")}`);
  process.exit(1);
}

let sql = `-- AUTO-GENERATED by buildCatalogNavigationStagingDelta.js - do not edit.
-- v9 CATALOG NAVIGATION/FACET DELTA - DISPOSABLE STAGING ONLY.
-- Apply after comparison_staging_delta.sql.
-- Contains no credentials and performs no connection of any kind.
`;

for (const rel of sources) {
  sql += `\n\n-- ============================================================\n`;
  sql += `-- ${rel}\n`;
  sql += `-- ============================================================\n\n`;
  sql += readFileSync(resolve(root, rel), "utf8");
}

const output = resolve(root, "catalog_navigation_staging_delta.sql");
const hashFile = resolve(root, "catalog_navigation_staging_delta.sha256.txt");
writeFileSync(output, sql, "utf8");
const sha = createHash("sha256").update(Buffer.from(sql, "utf8")).digest("hex");
writeFileSync(hashFile, `${sha}  catalog_navigation_staging_delta.sql\n`, "utf8");

console.log(`✓ catalog_navigation_staging_delta.sql written (${Math.round(Buffer.byteLength(sql) / 1024)} KB)`);
console.log(`  sha256: ${sha}`);
console.log("  target: disposable staging only; bootstrap and production builder unchanged");
